version: "3.9"
services:

  db:
    build:
      context: .
      dockerfile: deployment/db/Dockerfile
      args:
        - SA_PASSWORD=$SA_PASSWORD
        - ACCEPT_EULA=$ACCEPT_EULA
        - MSSQL_PID=$MSSQL_PID
        - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
#  db:
#    image: microsoft/mssql-server-ubuntu
#    container_name: db
#    environment:
#      - ACCEPT_EULA=Y
#      - MSSQL_SA_PASSWORD=password123
#      - MSSQL_TCP_PORT=1433
#    ports:
#      - "1400:1433"

  api:
    build:
      context: .
      dockerfile: deployment/web/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

volumes:
  mssqldata: