version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/src
    ports:
      - 8000:8000

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      args:
        - SA_PASSWORD=$SA_PASSWORD
        - ACCEPT_EULA=$ACCEPT_EULA
        - MSSQL_PID=$MSSQL_PID
    ports:
      - 1433:1433