version: "3.9"
services:

  migrations:
    build:
      context: .
      dockerfile: deployment/migrations/Dockerfile
    volumes:
      - ./deployment/migrations/versions:/flyway/sql
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: deployment/db/Dockerfile
    env_file:
      - .env
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: deployment/api/Dockerfile
    volumes:
      - .:/src
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mssqldata: