version: "3.9"
services:

  db:
    build:
      context: .
      dockerfile: deployment/db/Dockerfile
      args:
        - SA_PASSWORD=$SA_PASSWORD
        - ACCEPT_EULA=$ACCEPT_EULA
        - MSSQL_PID=$MSSQL_PID
    ports:
      - 1433:1433

  api:
    build:
      context: .
      dockerfile: deployment/web/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db

volumes:
  mssqldata: